"""empty message

Revision ID: 39db00945cd0
Revises: 99bbd695e2e3
Create Date: 2023-07-06 13:06:07.360676

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39db00945cd0'
down_revision = '99bbd695e2e3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
