"""empty message

Revision ID: 541cae734ccd
Revises: 6e96c50eb972
Create Date: 2023-07-06 13:47:45.620461

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '541cae734ccd'
down_revision = '6e96c50eb972'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
